### ISSUE TITLE
doesn't play well with laravel installer and valet

### ISSUE THREAD

**Issue by edanisko** [thedevdojo/genesis#10]
Once I'm installed and run pnpm dev I get:
```
laravel new genesis
cd genesis
composer require devdojo/genesis dev-main
php arisan ui genesis
pnpm i # serisouly... npm?
pnpm upgrade
pnpm run dev

  VITE v4.0.0  ready in 365 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help

  LARAVEL v10.18.0  plugin v0.7.8

  ➜  APP_URL: http://genesis.test

```

The APP_URL is set by using the laravel installer. Vite is using .env's APP_URL to grab that link.

The docs are ambiguous about how to install laravel.

---

If you use:

```
laravel new genesis-test
```

Your APP_URL will be:

```
APP_URL=http://genesis-test.test
```

then:

```
valet link
```

Which kinda works for the home page but I get gateway errors trying to create a user or login.

---

If you use:

```
composer create-project laravel/laravel example-app-or-wtvr
```

Your APP_URL will be:

```
APP_URL=http://localhost
```

Then even:

```
php artisan serve
```

Launches at http://127.0.0.1:8000 while Vite is sending the user to http://localhost which breaks.

---

I'm sure there is magic here that can be done to figure this out.  

But for now, I think you should mention in the README about setting the APP_URL.  Maybe with some hints about what was used to install laravel.  

PR Incoming.

**Comment by tnylea** [comment]
Thanks! Merging in your PR and I'll keep this open as a reminder to find a better way of showing how it all works with a new Laravel application 👍

**Comment by tnylea** [comment]
Quick question,

Why are you choosing to use PNPM over NPM?

Does it work fine when you use NPM command?

LMK
