### ISSUE TITLE
Bug: Delete Account Modal Not Displayed When Toast Popup Appears

### ISSUE THREAD

**Issue by arifbudimanarrosyid** [thedevdojo/genesis#17]
The name and email update works well, but the delete account modal doesn't show up when there's a toast message. To see the delete account modal, you might need to refresh the page.

**Comment by tnylea** [comment]
Would you mind recording a Loom for this issue: https://www.loom.com, it's a simple chrome extension where you can install and record a quick video of the issue.

Thanks man 😉

**Comment by arifbudimanarrosyid** [comment]
https://github.com/thedevdojo/genesis/assets/48200892/56dfdf66-b011-4538-9b41-238af54638b4

**Comment by arifbudimanarrosyid** [comment]
Sure here is the video
https://youtu.be/MdDiTROVwB0

**Comment by tnylea** [comment]
Thanks @arifbudimanarrosyid 

This should now be fixed in the latest version. We've also added named routes and updated Livewire, Volt, and Folio to the latest beta version 😉

Send over any other issues you experience. Appreciate it!
