### ISSUE TITLE
Bug : weird div behaviour on login and register page when use landscape mobile device

### ISSUE THREAD

**Issue by arifbudimanarrosyid** [thedevdojo/genesis#21]
Check out the login page, register page then open mobile simulator and make it landscape.
The logo, title, and link aren't scrollable.

And maybe impact on verifyemail page also, I have not set it up mailtrap yet.

To make it more clear pls see the video
https://youtu.be/chbRpPFvj-4

**Comment by tnylea** [comment]
I think this can be resolved by changing `h-screen` to `sm:h-screen h-auto` in the login/register/verify pages. I can take a look at that tomorrow unless you wanted to submit a PR that I could look at.

Thanks man 🤙

**Comment by tnylea** [comment]
Thanks for fixing that 😉

Just merged in: https://github.com/thedevdojo/genesis/pull/22
