### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by mai1237** [thedevdojo/genesis#25]
It would nice if you add sidebar as whell

**Comment by tnylea** [comment]
Can you ellaborate a little more. Send over screenshots or a little more detail and I'm sure we can look into it a little more 👍

**Comment by mai1237** [comment]
About Sidebar i have in my mind something like AdminLTE4 build around bootstrap
I sand you a url to see as sample.
https://adminlte-v4.netlify.app/dist/pages/index.html

**Comment by tnylea** [comment]
Aha, yeah. So, you are talking about having a sidebar menu in the admin section of the application, correct?

**Comment by mai1237** [comment]
Yes

**Comment by tnylea** [comment]
Great, Thanks for the suggestion. I've added it to the list of 'Nice-to-haves' for future versions ;)

https://github.com/orgs/thedevdojo/projects/2

Talk to you later.
