### ISSUE TITLE
Index page have comments in html.

### ISSUE THREAD

**Issue by hcijr6** [thedevdojo/genesis#4]
First clean installation and i see this. Hopefully you can find the error.
![image](https://github.com/thedevdojo/genesis/assets/57660681/70cf1291-96da-4d58-ba7e-04f833bd1846)

**Comment by tnylea** [comment]
Yep, that's actually an issue that Livewire V3 and Volt beta are resolving. While those are in Beta you may run into this and you can clear it with `php artisan view:clear`

It's also listed in the README.md here: https://github.com/thedevdojo/genesis#troubleshooting

Let me know if that helps ;) and let me know if you have any other issues.

Thanks!

**Comment by hcijr6** [comment]
Yes, that was all, now works perfectly. Congrats.
