### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by ondrejehrlich** [thedevdojo/genesis#7]
Hi
Thank you for this amazing tool. Just a quick thought: any chance of adding two-factor authentication like in Laravel Jetstream?

Many thanks.

**Comment by tnylea** [comment]
Sure thing, I've created a to-do list and added that item here: https://github.com/orgs/thedevdojo/projects/2 I'll be adding more items to this list :)

Thanks for the suggestion 😉
